remote_theme: samarsault/plainwhite-jekyll
# theme: plainwhite

title: decorus-kazuma's blog.
author: decorus-kazuma
email: brightdelusion@gmail.com
description: >
  What is a best practice?
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass

plainwhite:
  name: Kazuma Itou
  tagline: Software Enginner ğŸ‡¯ğŸ‡µ and ğŸ‡°ğŸ‡·
  date_format: "%b %-d, %Y"
  analytics_id: "UA-112777515-1"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/portfolio.jpeg"
  html_lang: "ko"
  condensed_mobile:
    - page
    - post
    - home
    - series
    - engineering
    - law
    - categories
    - tags
  navigation:
    - title: "ğŸ  Home"
      url: "/"
    - title: "ğŸš€ Series"
      url: "/series"
    - title: "ğŸ§‘ğŸ»â€ğŸ’» Engineering"
      url: "/engineering"
    - title: "ğŸ”¤ Language"
      url: "/language"
    - title: "âš–ï¸ Law"
      url: "/law"
    - title: "ğŸ§³ Categories"
      url: "/categories"
    - title: "ğŸ”– Tags"
      url: "/tags"
  social_links:
    github: decorus-kazuma
    linkedIn: in/decorus-kazuma
    email: brightdelusion@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-regex-replace
